Fix our backend samples
Our backend samples no longer work on OCP 4.14 and they fail the `oc
kustomize` call with:

 error: invalid Kustomization: json: cannot unmarshal string into Go
 struct field Kustomization.patches of type types.Patch

In this patch we update the `patches` section from:

 patches:
   - backend

to

 patches:
   - path: backend